// Generado por web_i18n/i18n_rebuild.js (eu) a partir de web/js/maps.js. No editar a mano: editar la memoria tm/eu.json y regenerar.
const MAPS = {
 "map-fil-que-es": {
  "subject": "fil",
  "tema": "Filosofia · 1. gaia",
  "title": "Zer da filosofia?",
  "md": "# Zer da filosofia?\n## Jakinduriarekiko maitasuna\n- *Philía* (maitasuna) + *sophía* (jakinduria)\n- Filosofoak egia **bilatzen** du, ez du bere egiten\n- **Harridura**tik, jakin-minetik eta zalantzatik sortzen da\n- «Ezer ez dakidala bakarrik dakit» (**Sokrates**)\n## Mitotik logosera\n- Grezia, **K.a. VI. mendea**\n- **Mitoa**: jainkoen kontakizuna; antropomorfikoa, arbitrarioa, **dogmatikoa**\n- **Logosa**: kausa naturalak eta **argudioak**; **kritikoa**\n- **Tales Miletokoa**k **arkhé**a bilatzen du\n## Jakite motak\n- **Arrunta**: berezkoa, ez hausnartua\n- **Zientifikoa**: hurbileko kausak; **partziala**\n- **Filosofikoa**: azken kausak; errealitatea **bere osotasunean**\n## Jakite filosofikoaren ezaugarriak\n- **Arrazionala** eta **kritikoa**\n- **Erradikala**: errora doa\n- **Unibertsala** eta **sistematikoa**\n- **Praktikoa**: etika eta politika\n- **Irekia** eta **historikoa**\n## Adarrak\n- **Metafisika**: zer den izatea, zer dagoen\n- **Ezagutzaren teoria**: zer ezagut dezakegu\n- **Etika** eta **filosofia politikoa**\n- **Estetika**, **logika** eta **antropologia**\n## Beste jakiteekin\n- **Zientzia**: datuak eta esperimentuak\n- **Erlijioa**: fedea eta errebelazioa\n- **Artea**: sentiarazten duten lanak\n- **Filosofia**: kontzeptuak eta argudioak\n## Zertarako balio du\n- Norberak pentsatzeko\n- **Testuak** irakurtzeko eta iruzkintzeko"
 },
 "map-filosofia-ciencia": {
  "subject": "fil",
  "tema": "Filosofia · Zientziaren filosofia",
  "title": "Zientziaren filosofia",
  "md": "# Zientziaren filosofia\n## Galdera nagusiak\n- Zer da **ezagutza zientifikoa**?\n- Nola lortzen da?\n- Zerk bereizten du zientzia beste jakintzetatik?\n## Fisikaren filosofia\n- **Espazioa eta denbora** — Newton vs Leibniz; erlatibitatea; kuantika\n- **Kausalitatea** — determinismoa vs indeterminismoa\n## Epistemologia zientifikoa\n- **Errealismoa** — teoriek egia deskribatzen dute\n- **Instrumentalismoa** — teoriak tresnak dira\n- Ezagutzaren **eraikuntza soziala**\n- Froga: **indukzioa**, **faltsazioa** (Popper), Bayesen teorema\n## Metodologia\n- **Metodo zientifikoa** — behaketa, hipotesia, esperimentazioa, teoria\n- Sailkapena: zientzia formalak, fisikoak, biologikoak eta sozialak\n## Matematikaren filosofia\n- **Platonismoa** — objektu matematikoak existitzen dira\n- **Nominalismoa** — hizkuntza soilik dira\n- **Intuizionismoa** — giza eraikuntza bat dira\n## Zientziaren historia\n- Iraultzak: **Koperniko**, **Newton**, **Einstein**, kuantika\n- **Galileo** — iraultza zientifikoaren hasiera"
 },
 "map-ser-humano": {
  "subject": "fil",
  "tema": "Filosofia · 2. gaia",
  "title": "Zer da gizakia?",
  "md": "# Zer da giza izakia?\n## Natura eta kultura\n- **Eboluzioa** → **hominizazioa** (biologikoa)\n- **Kultura** → **humanizazioa** (ikasia)\n- Natura-kultura dialektika; «amaitu gabe» jaiotzen gara\n## Kultura, nortasuna eta aniztasuna\n- **Sozializazioa**; nortasun pertsonal eta kolektiboa\n- **Etnozentrismoa / erlatibismoa / kulturartekotasuna**\n## Gorputza eta gogoa\n- **Dualismoa** — Platon (arimaren kartzela); Descartes (res cogitans / res extensa)\n- **Monismoa / materialismoa** — gorputza gara\n- Aristoteles — arima, gorputzaren **forma**\n## Kontzepzioak historian\n- Antzinatea — animalia **arrazional** eta soziala\n- Erdi Aroa — Jainkoaren irudira sortutako izakia\n- Modernitatea — pentsatzen duen subjektua (Descartes); **duintasuna** (Kant)\n- Garaikidea — Marx (lana), Nietzsche, existentzialismoa (**proiektua** eta askatasuna)\n## Kontzientzia, hizkuntza eta pertsona\n- **Kontzientzia** eta autokontzientzia (introspekzioa)\n- **Hizkuntza** sinbolikoa\n- **Pertsona** — duintasuna; berezko xedea\n## Nortasun pertsonala\n- Teseoren ontzia; **memoria** (Locke); Hume; kontakizuna\n- **Transhumanismoa**\n## Existentziaren zentzua\n- Absurdua / transzendentea / immanentea / **norberak zentzua ematea**"
 },
 "map-conocimiento": {
  "subject": "fil",
  "tema": "Filosofia · 3. gaia",
  "title": "Zer ezagut dezakegu?",
  "md": "# Zer ezagut dezakegu?\n## Giza ezagutza\n- **Subjektu — objektu** harremana\n- Mailak: **sentsazioa → pertzepzioa → kontzeptua** (abstrakzioa)\n- Adarra: **epistemologia / gnoseologia**\n## Ezagutzaren iturriak\n- **Arrazionalismoa** (Descartes) — arrazoia; jaiotzetiko ideiak\n- **Enpirismoa** (Locke, Hume) — esperientzia; *tabula rasa*\n- **Kritizismoa** (Kant) — esperientzia + arrazoia\n## Egiara irits gaitezke?\n- **Dogmatismoa** · **Eszeptizismoa** · **Erlatibismoa** · **Kritizismoa**\n## Egiaren auzia\n- Iritzia (**doxa**) zientziaren aurrean (**episteme**)\n- Teoriak: **korrespondentzia**, koherentzia, adostasuna, pragmatikoa\n## Post-egia\n- Gertaerek emozioek baino gutxiago pisatzen dute\n- Gezurrak, **fake news**, alborapenak, oihartzun-ganberak\n- Defentsa: **pentsamendu kritikoa** eta iturriak alderatzea\n## Jakintza zientifikoa\n- Zientzia **formalak** eta **enpirikoak** (naturalak / sozialak)\n- **Metodo hipotetiko-deduktiboa**; Popper (faltsagarritasuna), Kuhn (paradigmak)\n## Zientzia, teknologia eta artea\n- Zientzia / teknika / **teknologia**; muga etikoak\n- **Emakumea zientzian**"
 },
 "map-racionalismo-empirismo": {
  "subject": "fil",
  "tema": "Filosofia · Arrazionalismoa eta enpirismoa",
  "title": "Arrazionalismoa vs. enpirismoa",
  "md": "# Arrazionalismoa vs. enpirismoa\n## Arazoa\n- Aro Modernoa: zein da **ezagutzaren oinarria**?\n## Arrazionalismoa\n- Ordezkaria: **Descartes**\n- Iturria: **arrazoia** — **a priori** ezagutza\n- **Jaiotzetiko ideiak**: Jainkoa (res infinita), res cogitans, res extensa\n- **Dogmatismoa**: ez du arrazoiaren gaitasuna zalantzan jartzen\n- Egia **unibertsal eta beharrezkoak**\n- Metodo **deduktiboa**; eredua: **matematika**\n## Enpirismoa\n- Ordezkariak: **Locke** eta **Hume**\n- Iturria: **esperientzia** — **a posteriori** ezagutza\n- Locke — gogoa jaiotzean **tabula rasa** da\n- Hume — **kausalitatea** zalantzan jartzen du (ohitura) → **eszeptizismoa**\n- Egia orokor eta **behin-behinekoak**\n- Metodo **induktiboa**; eredua: **zientzia esperimentala**\n## Sintesia: Kant\n- **Kritizismoak** arrazoia eta esperientzia lotzen ditu\n- Filosofia, metafisika eta zientzia birdefinitzen ditu"
 },
 "map-fil-mito-logos": {
  "subject": "fil",
  "tema": "Filosofia · 1. gaia",
  "title": "Mitotik logosera",
  "md": "# Mitotik logosera\n## Urrats erabakigarria\n- Grezia, **K.a. VI. m.**: filosofia jaiotzen da\n- **Jainkoengatik** azaltzetik **arrazoiengatik** azaltzera\n## Mitoa (mythos)\n- **Jainkoen** kontakizunak, borondate apetatsukoak\n- **Antropomorfikoa eta animista**\n- Ahozko tradizioz transmititzen da\n- **Dogmatikoa**: eztabaidatu gabe onartzen da\n## Logosa (arrazoia)\n- **Kausa naturalak** eta legeak bilatzen ditu\n- **Argudioetan** oinarritzen da; egilea du\n- **Kritikoa**: eztabaida eta berrikus daiteke\n## Lehen filosofoak\n- **Arkhea** bilatzen dute (guztiaren printzipioa)\n- **Tales Miletokoa**: ura\n- Erabakigarria: **metodo-aldaketa**"
 },
 "map-fil-logica": {
  "subject": "fil",
  "tema": "Filosofia · 4. gaia",
  "title": "Logika eta argudiaketa",
  "md": "# Logika eta argudiaketa\n## Zer aztertzen du logikak\n- Arrazoiketen **zuzentasuna**\n- Pentsamenduaren **forma**, ez haren edukia\n- **Aristotelesek** sortu zuen (**silogismoaren** teoria)\n## Proposizioak eta argudioak\n- **Proposizioa**: egiazkoa edo faltsua den enuntziatua\n- **Argudioa**: **ondorio** bati eusten dioten **premisak**\n- Argudiatzea **arrazoiak ematea** da\n## Arrazoitzeko moduak\n- **Dedukzioa**: ondorio **beharrezkoa**\n- **Indukzioa**: kasuetatik orokorrera; **probablea** soilik\n- **Abdukzioa**: **azalpenik onena** (Peirce)\n- **Analogia**: antzekotasun esanguratsuak; **analogia faltsuaren** arriskua\n## Baliozkotasuna eta egia\n- **Baliozkotasuna**: **formaren** ezaugarria\n- **Egia**: **edukiaren** ezaugarria\n- **Sendoa** = baliozkoa + premisa egiazkoak\n- Indukzio bat ez da baliozkoa edo baliogabea, **indartsua** edo **ahula** baizik\n## Logika formala eta sinbolikoa\n- **Frege**: lehen mailako logika\n- **Konektiboak** eta **egia-taulak**; **tautologia** eta **kontraesana**\n- **Boole** eta **Shannon**: logikatik **ate logikoetara**\n- Gezurtiaren **paradoxa**\n## Falaziak\n- Baliozkoak dirudite, baina ez dira\n- **Formalak** (forma) eta **informalak** (edukia edo hizkuntza)\n- *Ad hominem*, *ad populum*, lastozko gizona, kausa faltsua…\n- **Sofisma** (nahita) eta **paralogismoa** (nahi gabe)\n## Aztertu eta elkarrizketatu\n- Adierazleak; **premisa inplizituak** (**entimema**)\n- **Frogaren zama** eta **karitatearen printzipioa**\n- **Kontraadibidea** eta **absurdura eramatea**\n- Arrazoitu, ez **arrazionalizatu**\n## Definitu eta bereizi\n- **Genero hurbila** + **diferentzia espezifikoa**\n- Baldintza **beharrezkoa** eta **nahikoa**\n- **Kontzeptu-analisia**: zer da gezurra esatea?"
 },
 "map-fil-etica": {
  "subject": "fil",
  "tema": "Filosofia · 5. gaia",
  "title": "Etikaren galderak",
  "md": "# Etikaren galderak\n## Etika eta morala\n- **Morala**: komunitate batean indarrean dauden arauak eta balioak\n- **Etika**: moralari buruzko hausnarketa filosofikoa\n- «Nola bizi behar dugu?» (**Sokrates**)\n- Mailak: etika **normatiboa**, **aplikatua** eta **metaetika**\n## Askatasuna, moralaren baldintza\n- Askatasunik gabe ez dago **erantzukizunik**\n- **Autonomia** **heteronomiaren** aurrean (Kant)\n- **Inkonpatibilismoa** eta **konpatibilismoa**\n## Etika materialak\n- **Ongia** edo helburua zein den esaten dute: **teleologikoak**\n- **Aristoteles**: *eudaimonia*; bertutea **erdibide** gisa\n- **Epikuro**: plazera *ataraxia* gisa\n- **Utilitarismoa** (Bentham, Mill): «zoriontasun handiena kopuru handienarentzat»\n## Kanten etika formala\n- **Deontologikoa**: **betebeharragatik** jardutea\n- **Inperatibo kategorikoa**: **lege unibertsal** izan daitekeen maxima\n- Gizateria, beti **helburu** gisa eta inoiz ez bitarteko soil gisa\n## Ba al dago egia moralik?\n- **Objektibismoa**: guztientzat balio duten egitate moralak\n- **Subjektibismoa** eta **erlatibismo kulturala**\n- **Ez-kognitibismoa**: **emotibismoa** (Hume, Ayer)\n- Kritikarik gabe ez dago **aurrerapen moralik**\n## Judizio morala\n- **Piaget**: moral **heteronomotik** **autonomora**\n- **Kohlberg**: hiru maila; **Heinzen dilema**\n- **Gilligan**: **zaintzaren** ahotsa\n## Susmoa eta muturreko kasuak\n- **Nietzsche**: **jaunen** eta **esklaboen** morala; **transbalorazioa**\n- Utilitarismoa proban: **tranbia** eta transplantea\n- **Singer**: gehiegi eskatzen al du?\n## Etika aplikatua gaur\n- **Zaintzaren etika** (Noddings, Tronto)\n- **Bioetika**: autonomia, ongintza, ez-kaltetzea eta justizia\n- **Animalia**-etika (**espezismoa**) eta **AAren** etika"
 },
 "map-fil-politica": {
  "subject": "fil",
  "tema": "Filosofia · 6. gaia",
  "title": "Bizitza gizartean",
  "md": "# Bizitza gizartean\n## Animalia politikoa\n- **Aristoteles**: *zoon politikon*\n- Bakartuta bizi dena «piztia bat edo jainko bat da»\n- Filosofia politikoak galdetzen du nolakoak **beharko** luketen gizarteek\n## Zergatik dago Estatua?\n- Antzinakoak: komunitate politikoa **naturala** da\n- Modernoak: artifizio bat, **gizarte-kontratua**\n- **Naturazko egoera**: hipotesi bat, ez gertakari bat\n- Kritikak: **Hume** (konkista eta onura) eta **Kant** (arrazoimenaren ideia)\n## Kontraktualistak\n- **Hobbes**: guztien gerra guztien aurka → **Leviatana**\n- **Locke**: eskubide naturalak → **Estatu liberala** eta erresistentzia-eskubidea\n- **Rousseau**: **borondate orokorra** → **herri-subiranotasuna**\n## Boterea eta legitimitatea\n- **Boterea**: besteek obedi dezaten lortzea\n- **Legitimitatea**: agintzeko eskubidea\n- **Weber**: tradizioa, karisma eta **legezkotasun arrazionala**\n## Justizia\n- **Banatzailea** eta **zuzentzailea** (Aristoteles)\n- **Rawls**: **ezjakintasunaren estalkia** eta **diferentziaren printzipioa**\n- **Nozick**: titulartasuna eta **Estatu minimoa**\n- **Komunitarismoa** (Sandel): partekatzen ditugun ondasunak\n## Gobernu-formak\n- Bat, gutxi, asko: **monarkia**, **aristokrazia**, **politeia**\n- Endekatuak, norberaren interesean: **tirania**, **oligarkia** eta, Aristotelesentzat, **demokrazia**\n- Demokrazia modernoa: **liberala**, **deliberatiboa**, **parte-hartzailea**\n- Mehatxuak: **gehiengoaren tirania**, **populismoa**, barrutiko higadura\n## Eskubideak eta askatasuna\n- **Giza eskubideak** (1948): hiru **belaunaldi**\n- **Zuzenbide-estatua** **totalitarismoaren** aurrean (Arendt)\n- **Berlin**: askatasun **negatiboa** eta askatasun **positiboa**\n## Ituna irudikatu eta zabaldu\n- **Utopiak** (Platon, Moro) eta **distopiak** (Huxley, Orwell)\n- **Feminismoa**: patriarkatua, **sexua eta generoa**, intersekzionalitatea\n- «Ez da emakume jaiotzen: emakume egiten da» (**Beauvoir**)"
 },
 "map-fil-estetica": {
  "subject": "fil",
  "tema": "Filosofia · 7. gaia",
  "title": "Zer da artea?",
  "md": "# Zer da artea?\n## Estetika\n- **Edertasunari**, **arteari** eta **esperientzia estetikoari** buruz hausnartzen du\n- Grezierazko *aísthesis*: sentsazioa (**Baumgarten**)\n- Zerbait **bere horretan** kontenplatzea, haren erabilera bilatu gabe\n## Non dago edertasuna?\n- **Objektiboa** (klasikoa): proportzioa, harmonia, ordena eta neurria\n- Pitagorikoak, **Polikleto** (*Kanona*), Agustin, Tomas\n- **Subjektiboa** (modernoa): begiratzen duenaren plazera\n- Beste kategoria batzuk: **sublimea**, itsusia, tragikoa, komikoa\n## Gustu-judizioa\n- **Hume**: **kritikari gaitua**\n- **Kant**: **interesik gabea** eta **unibertsala kontzepturik gabe**\n- **Helbururik gabeko finalitatea**; edertasun **librea** eta **atxikia**\n## Artearen teoriak\n- **Imitazioa** (*mímesis*): errealitatea irudikatzea\n- **Adierazpena** (Erromantizismoa): egilearen emozioa\n- **Forma** (formalismoa): konposizioa, kolorea, erritmoa\n- **Instituzionala** (Danto, Dickie): artearen munduak onartzen duena\n## Artea eta egia\n- **Platon**: kopia baten kopia; arteak **engainatu** egiten du\n- **Aristoteles**: *mímesis* eta **katarsia**\n- **Hegel**: «**artearen amaiera**»\n- **Heidegger** eta **Gadamer**: artelanak mundu bat irekitzen du\n## Artea, emozioa eta morala\n- Arteak sentimenduak **hezten** ditu\n- **Schiller**: **jolasa** eta hezkuntza estetikoa\n- **Moralismoa** **autonomismoaren** aurrean («artea artearengatik»)\n## Artea eta politika\n- **Arte konprometitua** **artea artearengatik**-en aurrean\n- **Benjamin**: faxismoak **politika estetizatzen** du\n- **Adorno**: **kultura-industria**\n## Irudia gaur\n- **Duchamp** eta **ready-made**-a\n- **Benjamin**: erreproduzigarritasun teknikoa eta **auraren** galera\n- **Debord** (ikuskizuna) eta **Baudrillard** (**simulakroa**)\n- **Alfabetizazio bisuala**: modu kritikoan begiratzea"
 },
 "map-fil-metafisica": {
  "subject": "fil",
  "tema": "Filosofia · M",
  "title": "Errealitatea: zer dago eta nolakoa da?",
  "md": "# Errealitatea: zer dago eta nolakoa da?\n## Metafisika\n- Galdetzen du **zer existitzen den** eta nolakoa den azken batean\n- *Ta meta ta physika*; Aristotelesen «**lehen filosofia**»\n- **Ontologia**: zer motatako gauzak existitzen diren\n- Kritikak: **Kant** eta **Vienako Zirkulua**\n## Itxura eta errealitatea\n- **Parmenides**: izatea bakarra eta aldaezina da; aldaketa, itxura\n- **Platon**: mundu **sentigarria** eta **Ideien** mundua\n- **Bostrom**: **simulazioaren** argudioa\n## Zerez dago egina dena?\n- **Monismoa** (Spinoza), **dualismoa** (Descartes), **pluralismoa** (Enpedokles, Leibniz)\n- **Materialismoa**: dena da materia (Demokrito, Hobbes, fisikalismoa)\n- **Idealismoa**: «izatea hautemana izatea da» (**Berkeley**)\n## Substantzia, esentzia eta existentzia\n- **Aristoteles**: **substantzia** eta haren **akzidenteak**\n- **Hilemorfismoa**: **materia** + **forma**\n- **Ekintza** eta **potentzia**: horrela azaltzen da aldaketa\n- **Sartre**: «existentzia esentziaren aurretik dator»\n## Gogoa, gorputza eta AA\n- **Dualismoa**: nola eragiten diote elkarri? (Isabel Bohemiakoa)\n- **Identitatearen teoria**: garunaren egoerak\n- **Funtzionalismoa** (Putnam): gogoa bere funtzioaren bidez definitzen da\n- **Turing-en testa** **gela txinatarraren** aurrean (Searle)\n- Kontzientziaren **arazo zaila** (Chalmers)\n## Denbora eta aldaketa\n- **Heraklito**: dena aldatzen da (ibaia)\n- **Zenon**: Akiles eta dortoka\n- **Teseoren ontzia** (Plutarko): berbera al da oraindik?\n- **Newton** (denbora absolutua) **Leibnizen** (erlatiboa) aurrean; **Einstein**\n- **Presentismoa** eta **eternalismoa**\n## Askeak al gara?\n- **Determinismoa** (Laplaceren deabrua) eta **indeterminismoa**\n- **Determinismo gogorra**: askatasuna ilusio bat da\n- **Libertarismoa**: beste modu batera joka genezakeen\n- **Konpatibilismoa**: askea izatea **hertsadurarik** gabe jardutea da\n## Jainkoa existitzen al da?\n- Argudio **ontologikoa** (Anselmo)\n- Argudio **kosmologikoa** (bost bideak) eta **diseinuarena** (Paley)\n- Aurka: **gaizkiaren arazoa**; erantzuna: **teodizea**\n- Kasu berezia: **Pascalen apustua**\n- **Teismoa**, **ateismoa**, **agnostizismoa** eta **fideismoa**"
 },
 "map-fil-cuerpo-mente": {
  "subject": "fil",
  "tema": "Filosofia · 2. gaia",
  "title": "Gorputza eta gogoa",
  "md": "# Gorputza eta gogoa\n## Gogo-gorputz arazoa\n- **Bat** al gara ala **bi**?\n## Dualismoa (bi errealitate)\n- Gorputz **materiala** + arima **immateriala** (funtsezkoa)\n- **Platon** — arima hilezkorra, gorputza «kartzela»; gurdi hegalduna; arima 3 zatitan (arrazionala, suminkorra, irrikakorra)\n- **Descartes** — res cogitans (gogoa) vs res extensa (gorputz-makina)\n## Monismo materialista (errealitate bat)\n- **Gorputza** soilik dago; gogoa haren **jarduera** da (burmuina)\n- **Demokrito**, **Hobbes**, **La Mettrie** (gizaki makina); gaur egun, **Dennett** eta **Churchland** bikotea\n## Arazoak\n- Dualismoa: nola komunikatzen dira gogoa eta gorputza?\n- Monismoa: **libre** al gara ala kimika soilik?"
 }
};
